version: "3.6"

services:
  client:
    build:
      context: ../client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - "/app/node_modules"
      - "../client:/app"

  mysql:
    image: mysql:5.7.22
    ports:
      - 3306:3306
    volumes:
      - ../api/internal/schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "example"
    logging:
      driver: none
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"

  redis:
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: none
